---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
  - name: Create configuration file for containerd
    shell: |
      cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
      overlay
      br_netfilter
      EOF
  - name: Load modules
    shell: |
      sudo modprobe overlay
      sudo modprobe br_netfilter
  - name: Set system configurations for Kubernetes networking
    shell: |
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      EOF
  - name: Apply new settings
    shell: |
      sudo sysctl --system
  - name: Install containerd
    shell: |
      sudo apt-get update && sudo apt-get install -y containerd
  - name: Create default configuration file for containerd
    shell: |
      sudo mkdir -p /etc/containerd
  - name: Generate default containerd configuration and save to the newly created default file
    shell: |
      sudo containerd config default | sudo tee /etc/containerd/config.toml
  - name: Restart containerd to ensure new configuration file usage
    shell: |
      sudo systemctl restart containerd
  - name: Verify that containerd is running
    shell: |
      sudo systemctl status containerd
  - name: Disable swap
    shell: |
      sudo swapoff -a