---
- hosts: master
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
 
  - name:  Join Kubernetes Node in Cluster with this command...
    become: yes
    become_user: ubuntu
    shell: kubeadm token create  --print-join-command
    register: kubernetes_join_command

  - debug:
      msg: "{{ kubernetes_join_command.stdout }}"
  - name: Copy join command to local file.
    become: yes
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777



- hosts: nodes
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
   - name: Copy join command from Ansiblehost to the worker nodes.
     become: yes
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: Join the Worker nodes to the cluster.
     become: yes
     command: sudo sh /tmp/kubernetes_join_command
     register: joined_or_not
   - debug:
        msg: "{{ joined_or_not.stdout }}"